package org.modeshape.connector.cmis.operations.impl;

import org.apache.chemistry.opencmis.client.api.ObjectType;
import org.apache.chemistry.opencmis.client.api.Session;
import org.apache.chemistry.opencmis.commons.enums.BaseTypeId;
import org.apache.chemistry.opencmis.commons.exceptions.CmisObjectNotFoundException;
import org.infinispan.schematic.document.Document;
import org.infinispan.schematic.document.EditableDocument;
import org.modeshape.connector.cmis.operations.CmisObjectFinderUtil;
import org.modeshape.connector.cmis.ObjectId;
import org.modeshape.connector.cmis.features.SingleVersionDocumentsCache;
import org.modeshape.connector.cmis.features.SingleVersionOptions;
import org.modeshape.connector.cmis.features.TempDocument;
import org.modeshape.connector.cmis.mapping.LocalTypeManager;
import org.modeshape.connector.cmis.mapping.MappedCustomType;
import org.modeshape.connector.cmis.operations.BinaryContentProducerInterface;
import org.modeshape.connector.cmis.operations.DocumentProducer;
import org.modeshape.jcr.JcrLexicon;
import org.modeshape.jcr.federation.spi.DocumentWriter;
import org.modeshape.jcr.value.Name;

import javax.jcr.nodetype.NodeType;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;

/*
 * Single Version Feature supporting operations
 *
 * Does creation of document in external system with a single action
 * which takes place when jcr submits document's content to store action
 * before that action all teh incoming data are stored in temporary document
 * held by connector
 *
 * Until document is create in external system jcr uses fake GUID
 * generated by connector to access the object
 *
 * However this guid must be kept by connector/externalCmis for
 * jcr to be able to query the document
 * thus, generated/fake guid is stored in the special custom property of an object
 * Property name is defined in SingleVersionOptions settings
 *
 * Having of such a property make connector to utilize extended document search approach
 * along with standard GetObject which is not able to find object by it's Fake GUID
 * as it is not known by external system
 *
 * Additional search logic is a query conducted and executed by connector
 *
 * note : Single version is applicable to documents only, so folders may be retrieved with standard getObject call
 * note : single version logic is applied to the types defined in SingleVersionOptions block
 * note : if incoming cmis object has <commonIdProperty> set it is considered as objectId
 *        even if document's type is not listed in SingleVersionOptions. Because SingleVersionOptions
 *        might had been changed after object is created.
 *
 */
public class CmisSingleVersionOperations extends CmisOperation {

    private SingleVersionOptions singleVersionOptions;
    private SingleVersionDocumentsCache singleVersionCache;
    private DocumentProducer documentProducer;

    public CmisSingleVersionOperations(Session session, LocalTypeManager localTypeManager, CmisObjectFinderUtil fUtil,
                                       SingleVersionOptions singleVersionOptions,
                                       SingleVersionDocumentsCache singleVersionCache,
                                       DocumentProducer documentProducer) {
        super(session, localTypeManager, fUtil);
        this.singleVersionOptions = singleVersionOptions;
        this.singleVersionCache = singleVersionCache;
        this.documentProducer = documentProducer;
    }

    /*
    * if requested id presented in temporary documents cache then
    * it's ought to be saved as single version
    */
    public boolean doStoreAsSingleVersion(ObjectId objectId) {
        return singleVersionCache.containsKey(objectId.getIdentifier());
    }

    /*
    * create external document and drop cached local Temporary object
    * and its references
    */
    public void storeDocument(ObjectId objectId, Document document, CmisNewObjectCombinedOperation cmisStoreOperation,
                              BinaryContentProducerInterface binaryContentProducer) {
        TempDocument tempDocument = singleVersionCache.get(objectId.getIdentifier());
        if (objectId.getType() == ObjectId.Type.CONTENT) {
            cmisStoreOperation.storeDocument(
                    tempDocument.getParentId(), tempDocument.getName(), tempDocument.getPrimaryType(),
                    tempDocument.getDocument(),
                    document, binaryContentProducer);
            singleVersionCache.remove(objectId.getIdentifier());
            // seems must clean reference as well todo check
            singleVersionCache.removeReference(tempDocument.getParentId(), objectId.getIdentifier());
        } else {
            tempDocument.setDocument(document);
        }
    }

    /*
    * tests target type to define whether it has to be saved as singleVersion
    * criteria: type must be listed in SingleVersionOptions.singleVersionTypes + must be a descendant of cmis:document
    */
    public boolean doAsSingleVersion(Name primaryType) {
        MappedCustomType mappedType = localTypeManager.getMappedTypes().findByJcrName(primaryType.toString());
        String cmisObjectTypeName = mappedType.getExtName();
        // need to resolve jcr name to prefixed/humanReadable
        boolean doAsSingleVersion = singleVersionOptions.getSingleVersionTypeNames().contains(primaryType);
        ObjectType typeDefinition = localTypeManager.getTypeDefinition(session, cmisObjectTypeName);

        return doAsSingleVersion && typeDefinition.getBaseTypeId() == BaseTypeId.CMIS_DOCUMENT;
    }

    /*
    * stores incoming parameters in the cache
    * returns generated fake guid to jcr
    * optional prefix (configurable) as added to a generated guid
    *
    * additionally generated guid/name added to parent's references as virtual child
    */
    public String newDocumentId(String parentId,
                                Name name,
                                Name primaryType) {

        String newGUID = singleVersionOptions.getSingleVersionGUIDPrefix() + UUID.randomUUID().toString();
        String resultGuid = singleVersionOptions.commonIdValuePreProcess(newGUID);
        TempDocument value = new TempDocument(parentId, name, primaryType);
        singleVersionCache.put(resultGuid, value);
        // parent
        List<String> childValues = singleVersionCache.getReferences(parentId);
        if (childValues == null) childValues = new ArrayList<String>();
        childValues.add(resultGuid);
        singleVersionCache.putReferences(parentId, childValues);

        return resultGuid;
    }

    /*
    * appends virtual children to an object
    * those virtual children are temp documents that not yet created in the external repository
    * but already attached to parent by jcr/modeshape
    */
    public void addCachedChildren(String id, DocumentWriter writer) {
        if (singleVersionCache.containsReferences(id)) {
            List<String> strings = singleVersionCache.getReferences(id);
            for (String childId : strings) {
                TempDocument tempDocument = singleVersionCache.get(childId);
                if (tempDocument != null)
                    writer.addChild(childId, tempDocument.getName().getLocalName());
            }
        }
    }

    /*
    * return a virtual document or content requested by JCR using generated fake guid
    * these are documents that are not yet created in the external system
    *
    * todo validate that returning of empty CONTENT node does not affect performance, or else construct virtual CONTENT document
    */
    public Document getCachedTempDocument(ObjectId suggestedObjectId) {
        TempDocument theParams = singleVersionCache.get(suggestedObjectId.getIdentifier());
        if (theParams.getDocument() != null) {
            Document document = theParams.getDocument();
            System.out.println("Return cached document:: " + document);
            return document;
        }
        if (suggestedObjectId.getType() == ObjectId.Type.OBJECT) {
            DocumentWriter writer = documentProducer.getNewDocument(suggestedObjectId.toString());
            // set correct type
            writer.setPrimaryType(theParams.getPrimaryType());
            // parents
            writer.setParents(ObjectId.toString(ObjectId.Type.OBJECT, theParams.getParentId()));
            // fill properties?
            // reference
            writer.addMixinType(NodeType.MIX_REFERENCEABLE);
            writer.addProperty(JcrLexicon.UUID, suggestedObjectId.toString());
            // content node - mandatory child for a document
//                writer.addChild(ObjectId.toString(ObjectId.Type.CONTENT, id), JcrConstants.JCR_CONTENT);
            EditableDocument document = writer.document();
            System.out.println("Return cached document by init params:: " + document);
            return document;
        } else if (suggestedObjectId.getType() == ObjectId.Type.CONTENT) {
            return null;
                /*String contentId = ObjectId.toString(ObjectId.Type.CONTENT, objectId.getIdentifier());
                DocumentWriter writer = newDocument(contentId);

                writer.setPrimaryType(NodeType.NT_RESOURCE);
                writer.setParent(objectId.getIdentifier());

                // reference
                writer.addMixinType(NodeType.MIX_REFERENCEABLE);
                writer.addProperty(JcrLexicon.UUID, contentId);*/

//                Property<Object> lastModified = doc.getProperty(PropertyIds.LAST_MODIFICATION_DATE);
//                Property<Object> lastModifiedBy = doc.getProperty(PropertyIds.LAST_MODIFIED_BY);

//                writer.addProperty(JcrLexicon.LAST_MODIFIED, localTypeManager.getPropertyUtils().jcrValues(lastModified));
//                writer.addProperty(JcrLexicon.LAST_MODIFIED_BY, localTypeManager.getPropertyUtils().jcrValues(lastModifiedBy));

//                writer.addMixinType(NodeType.MIX_CREATED);
//                Property<Object> created = doc.getProperty(PropertyIds.CREATION_DATE);
//                Property<Object> createdBy = doc.getProperty(PropertyIds.CREATED_BY);
//                writer.addProperty(JcrLexicon.CREATED, localTypeManager.getPropertyUtils().jcrValues(created));
//                writer.addProperty(JcrLexicon.CREATED_BY, localTypeManager.getPropertyUtils().jcrValues(createdBy));

                /*EditableDocument document = writer.document();
                System.out.println("Return cached document content by init params:: " + document);
                return document;*/
        }
        throw new CmisObjectNotFoundException("Cached object is not found under given key");
    }
}
